vti_encoding:SR|utf8-nl
vti_author:SR|IDMI\\Cunningham
vti_modifiedby:SR|IDMI\\Cunningham
vti_timelastmodified:TR|13 Nov 2009 01:54:00 -0000
vti_timecreated:TR|13 Nov 2009 01:44:43 -0000
vti_lineageid:SR|{6CE25752-9A0D-4FB2-AC43-0AD3EB48AD51}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|13 Nov 2009 01:48:01 -0000
vti_cacheddtm:TX|13 Nov 2009 01:54:00 -0000
vti_filesize:IR|6345
vti_sourcecontrolversion:SX|V1
vti_sourcecontrolcookie:SX|fp_internal
